---
config: baseline_seq2seq  # corresponds to a key in MODEL_CLASSES (see main.py)
architecture: seq2seq
type: baseline

max_input_length: 256
max_target_length: 128

encoder_args:
  hidden_dim: 768
  num_heads: 6
  num_layers: 6
  dim_feedforward: 2048
  dropout: 0.1

decoder_args:
  hidden_dim: 768
  num_heads: 6
  num_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
