---
config: syntax_augmented_trans

encoder_args:
  hidden_dim: 768
  num_heads: 6
  num_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
  d_vocab_size: 1000
  c_vocab_size: null
  u_vocab_size: null

decoder_args:
  hidden_dim: 768
  num_heads: 6
  num_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
