---
config: syntax_augmented_trans_gated

encoder_args:
  hidden_dim: 768
  num_heads: 6
  num_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
  syntax_gate: True

decoder_args:
  hidden_dim: 768
  num_heads: 6
  num_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
