---
defaults:
  - _self_
  - run: default
  - model: baseline_seq2seq
  - wandb: default
  - hydra: default

model:
  tokenizer_name_or_path: microsoft/codebert-base
  checkpoint: null

device: cuda
parallel: False
use_wandb: True
