---
defaults:
  - _self_
  - run: default
  - model: baseline_trans
  - wandb: default
  - hydra: default

model:
  tokenizer_name_or_path: microsoft/codebert-base
  checkpoint: null
  max_input_length: 256
  max_target_length: 128

device: cuda
parallel: False
use_wandb: True
