---
defaults:
  - _self_
  - run: default
  - model: baseline_trans
  - wandb: default

model:
  tokenizer_name_or_path: microsoft/codebert-base
  checkpoint: null
  vocab_size: 50265
  max_input_length: 256
  max_target_length: 128

device: cuda
parallel: False
# do not upload logs to wandb in dev mode
mode: dev
use_wandb: False

# remove output files in dev mode
hydra:
  output_subdir: null
  run:
    dir: .
