---
base_path: null   # leave it null

dataset_dir: dataset
dataset_lang: python

train_batch_size: 64
valid_batch_size: 64
learning_rate: 1e-4
epochs: 25
patience: 3

do_train: False
do_test: False
do_train_code_tokenizer: True
do_train_nl_tokenizer: False
seed: 42
